baseurl      = "/"
title        = "sheep's website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
copyright = '<a href="/license">License</a>'

enableEmoji     = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  # My config options
  enableThemeToggle = true
  
  homeTitle = "sheep"
  homeSubtitle = "A web developer from Zagreb, Croatia"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "sheep's personal website"
  keywords = "homepage, blog"
  images = [""]
  
  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/pages\">GitHub Pages</a>",
      "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]
   [params.portrait]  
     path     = "https://raw.githubusercontent.com/sheeepdev/website/main/img/pfp.png"
     alt      = "Logo"
     maxWidth = "75px"      

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "sheep's website"
    subtitle = ""
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sheep's website"
      logoHomeLink = "/"
      path = "https://raw.githubusercontent.com/sheeepdev/website/main/img/pfp.png"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts"
   [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"  
