baseurl      = "https://sheepdev.xyz/"
title        = "sheep's website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
copyright    = "© 2022"

enableEmoji     = true
enableRobotsTXT = true

[params.utterances]
	owner = "sheeepdev"
	repo = "website"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "Jan 2, 2006 | 15:04"

  # Metadata mostly used in document's head
  description = "sheep's personal website"
  keywords = "homepage, blog"
  images = [""]
  
  # Home stuff
  homeTitle = "sheep"
  homeSubtitle = "A software developer from Zagreb, Croatia"
  
  # Theme toggle
  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "<a href=\"https://sheepdev.xyz/privacy>Privacy Policy</a>",
      "Made with &#10084; by <a href=\"https://github.com/sheeepdev\">sheep</a>"
    ]
    
   [params.portrait]  
     path     = "https://raw.githubusercontent.com/sheeepdev/website/main/assets/sheep.png"
     alt      = "Logo"
     maxWidth = "75px"      

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
    name = "mastodon"
    url  = "https://fosstodon.org/@sheepdev"

  [[params.social]]
    name = "email"
    url  = "mailto:hi@sheepdev.xyz"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sheeepdev"

  [[params.social]]
    name = "discord"
    url ="https://discord.com/users/429303151598895106"

  [[params.social]]
  	name = "gpg"
  	url = "https://keys.openpgp.org/vks/v1/by-fingerprint/74AF0DA92EF9F99A705E3819B21C1AECF11929AD"


[languages]
  [languages.en]
    title = "sheep's website"
    subtitle = ""
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sheep"
      logoHomeLink = "/"
      logoCursorColor = "#3281ea"
    #  path = "https://raw.githubusercontent.com/sheeepdev/website/main/img/pfp.png"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts"
    weight     = "2" 
   [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about" 
    weight     = "1" 
   [[menu.main]]
    identifier = "uses"
    name       = "Uses"
    url        = "uses"
    weight     = "3"
   [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url		   = "projects"
    weight     = "4" 
   [[menu.main]]
   	identifier = "contact"
   	name 	   = "Contact"
   	url        = "contact" 
   	weight     = "5" 
